/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QGroupBox *groupBox;
    QLabel *label;
    QLabel *camStatus;
    QPushButton *displayPause;
    QPushButton *displayContinue;
    QPushButton *pushButton_CaptureSample;
    QGroupBox *groupBox_2;
    QLineEdit *portName;
    QLineEdit *portBaudRate;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QPushButton *portOpen;
    QPushButton *portClose;
    QLabel *portStatus;
    QGroupBox *groupBox_3;
    QGroupBox *groupBox_4;
    QCheckBox *obj1_usecheck;
    QGroupBox *obj1_usebox;
    QCheckBox *obj1_showres;
    QComboBox *obj1_distype;
    QLabel *label_21;
    QLineEdit *obj1_objpath;
    QPushButton *obj1_test;
    QPushButton *obj1_lock;
    QPushButton *obj1_stop;
    QComboBox *obj1_resswitch;
    QToolButton *Button_obj1_OpenDialog;
    QPushButton *pushButton_obj1_CaptureSample;
    QCheckBox *MoveR;
    QPushButton *obj_door;
    QLineEdit *obj1_objpath_2;
    QCheckBox *haveblock;
    QLabel *label_25;
    QLabel *obj1_objvalid;
    QGroupBox *groupBox_7;
    QCheckBox *obj2_usecheck;
    QGroupBox *obj2_usebox;
    QCheckBox *obj2_showres;
    QComboBox *obj2_distype;
    QLabel *label_26;
    QLineEdit *obj2_objpath;
    QPushButton *obj2_test;
    QPushButton *obj2_lock;
    QPushButton *obj2_stop;
    QComboBox *obj2_resswitch;
    QToolButton *Button_obj2_OpenDialog;
    QPushButton *pushButton_obj2_CaptureSample;
    QLabel *label_28;
    QLabel *obj2_objvalid;
    QGroupBox *groupBox_8;
    QCheckBox *obj3_usecheck;
    QGroupBox *obj3_usebox;
    QCheckBox *obj3_showres;
    QComboBox *obj3_distype;
    QLabel *label_29;
    QLineEdit *obj3_objpath;
    QPushButton *obj3_test;
    QPushButton *obj3_lock;
    QPushButton *obj3_stop;
    QComboBox *obj3_resswitch;
    QToolButton *Button_obj3_OpenDialog;
    QPushButton *pushButton_obj3_CaptureSample;
    QLabel *label_31;
    QLabel *obj3_objvalid;
    QGroupBox *groupBox_9;
    QCheckBox *obj4_usecheck;
    QGroupBox *obj4_usebox;
    QCheckBox *obj4_showres;
    QComboBox *obj4_distype;
    QLabel *label_32;
    QLineEdit *obj4_objpath;
    QPushButton *obj4_test;
    QPushButton *obj4_lock;
    QPushButton *obj4_stop;
    QComboBox *obj4_resswitch;
    QToolButton *Button_obj4_OpenDialog;
    QPushButton *pushButton_obj4_CaptureSample;
    QLabel *obj4_objvalid;
    QLabel *label_34;
    QGroupBox *groupBox_5;
    QLabel *label_17;
    QGroupBox *exec_hand;
    QPushButton *send_mvback2;
    QPushButton *send_turnleft;
    QPushButton *send_mvforward2;
    QPushButton *send_mvleft;
    QPushButton *send_kickright;
    QPushButton *send_mvforward1;
    QPushButton *send_mvright;
    QPushButton *send_kickleft;
    QPushButton *send_turnright;
    QPushButton *send_mvback1;
    QPushButton *send_wan;
    QPushButton *send_mvforward3;
    QPushButton *send_standpose;
    QPushButton *send_turnleft_big;
    QPushButton *send_turnright_big;
    QPushButton *head_left;
    QPushButton *head_right;
    QPushButton *head_up;
    QPushButton *head_down;
    QLabel *send_isaction;
    QLabel *label_5;
    QGroupBox *strategy_box;
    QPushButton *strategy_start;
    QLabel *label_19;
    QComboBox *strategy_type;
    QTextBrowser *strategy_imgdis;
    QLabel *label_20;
    QPushButton *strategy_stop;
    QPushButton *strategy_clearinfo;
    QTextBrowser *strategy_exec_orders;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(847, 699);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        groupBox = new QGroupBox(centralWidget);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(10, 0, 281, 81));
        label = new QLabel(groupBox);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 20, 101, 16));
        camStatus = new QLabel(groupBox);
        camStatus->setObjectName(QString::fromUtf8("camStatus"));
        camStatus->setGeometry(QRect(60, 20, 30, 16));
        displayPause = new QPushButton(groupBox);
        displayPause->setObjectName(QString::fromUtf8("displayPause"));
        displayPause->setGeometry(QRect(10, 40, 81, 23));
        displayContinue = new QPushButton(groupBox);
        displayContinue->setObjectName(QString::fromUtf8("displayContinue"));
        displayContinue->setGeometry(QRect(100, 40, 101, 23));
        pushButton_CaptureSample = new QPushButton(groupBox);
        pushButton_CaptureSample->setObjectName(QString::fromUtf8("pushButton_CaptureSample"));
        pushButton_CaptureSample->setGeometry(QRect(210, 40, 51, 23));
        groupBox_2 = new QGroupBox(centralWidget);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(370, 0, 411, 91));
        portName = new QLineEdit(groupBox_2);
        portName->setObjectName(QString::fromUtf8("portName"));
        portName->setGeometry(QRect(70, 60, 71, 20));
        portBaudRate = new QLineEdit(groupBox_2);
        portBaudRate->setObjectName(QString::fromUtf8("portBaudRate"));
        portBaudRate->setGeometry(QRect(220, 60, 81, 20));
        label_2 = new QLabel(groupBox_2);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(10, 60, 61, 20));
        label_3 = new QLabel(groupBox_2);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(160, 60, 61, 21));
        label_4 = new QLabel(groupBox_2);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(10, 20, 111, 21));
        portOpen = new QPushButton(groupBox_2);
        portOpen->setObjectName(QString::fromUtf8("portOpen"));
        portOpen->setGeometry(QRect(130, 20, 75, 23));
        portClose = new QPushButton(groupBox_2);
        portClose->setObjectName(QString::fromUtf8("portClose"));
        portClose->setGeometry(QRect(210, 20, 75, 23));
        portStatus = new QLabel(groupBox_2);
        portStatus->setObjectName(QString::fromUtf8("portStatus"));
        portStatus->setGeometry(QRect(60, 20, 30, 16));
        groupBox_3 = new QGroupBox(centralWidget);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(10, 80, 771, 341));
        groupBox_4 = new QGroupBox(groupBox_3);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(10, 20, 331, 141));
        obj1_usecheck = new QCheckBox(groupBox_4);
        obj1_usecheck->setObjectName(QString::fromUtf8("obj1_usecheck"));
        obj1_usecheck->setGeometry(QRect(10, 20, 131, 17));
        obj1_usecheck->setChecked(false);
        obj1_usebox = new QGroupBox(groupBox_4);
        obj1_usebox->setObjectName(QString::fromUtf8("obj1_usebox"));
        obj1_usebox->setGeometry(QRect(10, 30, 311, 101));
        obj1_showres = new QCheckBox(obj1_usebox);
        obj1_showres->setObjectName(QString::fromUtf8("obj1_showres"));
        obj1_showres->setGeometry(QRect(0, 10, 121, 17));
        obj1_showres->setChecked(true);
        obj1_distype = new QComboBox(obj1_usebox);
        obj1_distype->addItem(QString());
        obj1_distype->addItem(QString());
        obj1_distype->setObjectName(QString::fromUtf8("obj1_distype"));
        obj1_distype->setGeometry(QRect(180, 30, 61, 22));
        label_21 = new QLabel(obj1_usebox);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(0, 30, 71, 16));
        obj1_objpath = new QLineEdit(obj1_usebox);
        obj1_objpath->setObjectName(QString::fromUtf8("obj1_objpath"));
        obj1_objpath->setGeometry(QRect(0, 50, 90, 20));
        obj1_test = new QPushButton(obj1_usebox);
        obj1_test->setObjectName(QString::fromUtf8("obj1_test"));
        obj1_test->setGeometry(QRect(260, 20, 41, 23));
        obj1_lock = new QPushButton(obj1_usebox);
        obj1_lock->setObjectName(QString::fromUtf8("obj1_lock"));
        obj1_lock->setGeometry(QRect(260, 40, 41, 23));
        obj1_stop = new QPushButton(obj1_usebox);
        obj1_stop->setObjectName(QString::fromUtf8("obj1_stop"));
        obj1_stop->setGeometry(QRect(260, 60, 41, 23));
        obj1_resswitch = new QComboBox(obj1_usebox);
        obj1_resswitch->addItem(QString());
        obj1_resswitch->addItem(QString());
        obj1_resswitch->addItem(QString());
        obj1_resswitch->setObjectName(QString::fromUtf8("obj1_resswitch"));
        obj1_resswitch->setGeometry(QRect(180, 50, 61, 22));
        Button_obj1_OpenDialog = new QToolButton(obj1_usebox);
        Button_obj1_OpenDialog->setObjectName(QString::fromUtf8("Button_obj1_OpenDialog"));
        Button_obj1_OpenDialog->setGeometry(QRect(90, 30, 20, 20));
        pushButton_obj1_CaptureSample = new QPushButton(obj1_usebox);
        pushButton_obj1_CaptureSample->setObjectName(QString::fromUtf8("pushButton_obj1_CaptureSample"));
        pushButton_obj1_CaptureSample->setGeometry(QRect(90, 50, 51, 23));
        MoveR = new QCheckBox(obj1_usebox);
        MoveR->setObjectName(QString::fromUtf8("MoveR"));
        MoveR->setGeometry(QRect(140, 10, 71, 16));
        obj_door = new QPushButton(obj1_usebox);
        obj_door->setObjectName(QString::fromUtf8("obj_door"));
        obj_door->setGeometry(QRect(120, 30, 20, 20));
        obj1_objpath_2 = new QLineEdit(obj1_usebox);
        obj1_objpath_2->setObjectName(QString::fromUtf8("obj1_objpath_2"));
        obj1_objpath_2->setGeometry(QRect(0, 70, 91, 20));
        haveblock = new QCheckBox(groupBox_4);
        haveblock->setObjectName(QString::fromUtf8("haveblock"));
        haveblock->setGeometry(QRect(150, 20, 71, 16));
        label_25 = new QLabel(groupBox_4);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(230, 20, 81, 16));
        obj1_objvalid = new QLabel(groupBox_4);
        obj1_objvalid->setObjectName(QString::fromUtf8("obj1_objvalid"));
        obj1_objvalid->setGeometry(QRect(200, 10, 30, 16));
        groupBox_7 = new QGroupBox(groupBox_3);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(370, 10, 371, 151));
        obj2_usecheck = new QCheckBox(groupBox_7);
        obj2_usecheck->setObjectName(QString::fromUtf8("obj2_usecheck"));
        obj2_usecheck->setGeometry(QRect(20, 30, 171, 17));
        obj2_usebox = new QGroupBox(groupBox_7);
        obj2_usebox->setObjectName(QString::fromUtf8("obj2_usebox"));
        obj2_usebox->setGeometry(QRect(20, 40, 341, 101));
        obj2_showres = new QCheckBox(obj2_usebox);
        obj2_showres->setObjectName(QString::fromUtf8("obj2_showres"));
        obj2_showres->setGeometry(QRect(0, 20, 171, 17));
        obj2_distype = new QComboBox(obj2_usebox);
        obj2_distype->addItem(QString());
        obj2_distype->addItem(QString());
        obj2_distype->setObjectName(QString::fromUtf8("obj2_distype"));
        obj2_distype->setGeometry(QRect(210, 40, 61, 22));
        label_26 = new QLabel(obj2_usebox);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(0, 40, 71, 16));
        obj2_objpath = new QLineEdit(obj2_usebox);
        obj2_objpath->setObjectName(QString::fromUtf8("obj2_objpath"));
        obj2_objpath->setGeometry(QRect(0, 60, 91, 20));
        obj2_test = new QPushButton(obj2_usebox);
        obj2_test->setObjectName(QString::fromUtf8("obj2_test"));
        obj2_test->setGeometry(QRect(280, 30, 41, 23));
        obj2_lock = new QPushButton(obj2_usebox);
        obj2_lock->setObjectName(QString::fromUtf8("obj2_lock"));
        obj2_lock->setGeometry(QRect(280, 50, 41, 23));
        obj2_stop = new QPushButton(obj2_usebox);
        obj2_stop->setObjectName(QString::fromUtf8("obj2_stop"));
        obj2_stop->setGeometry(QRect(280, 70, 41, 23));
        obj2_resswitch = new QComboBox(obj2_usebox);
        obj2_resswitch->addItem(QString());
        obj2_resswitch->addItem(QString());
        obj2_resswitch->addItem(QString());
        obj2_resswitch->setObjectName(QString::fromUtf8("obj2_resswitch"));
        obj2_resswitch->setGeometry(QRect(210, 60, 61, 22));
        Button_obj2_OpenDialog = new QToolButton(obj2_usebox);
        Button_obj2_OpenDialog->setObjectName(QString::fromUtf8("Button_obj2_OpenDialog"));
        Button_obj2_OpenDialog->setGeometry(QRect(120, 40, 81, 21));
        pushButton_obj2_CaptureSample = new QPushButton(obj2_usebox);
        pushButton_obj2_CaptureSample->setObjectName(QString::fromUtf8("pushButton_obj2_CaptureSample"));
        pushButton_obj2_CaptureSample->setGeometry(QRect(120, 60, 81, 23));
        label_28 = new QLabel(groupBox_7);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(260, 30, 91, 16));
        obj2_objvalid = new QLabel(groupBox_7);
        obj2_objvalid->setObjectName(QString::fromUtf8("obj2_objvalid"));
        obj2_objvalid->setGeometry(QRect(190, 10, 30, 16));
        groupBox_8 = new QGroupBox(groupBox_3);
        groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
        groupBox_8->setGeometry(QRect(10, 170, 291, 171));
        obj3_usecheck = new QCheckBox(groupBox_8);
        obj3_usecheck->setObjectName(QString::fromUtf8("obj3_usecheck"));
        obj3_usecheck->setGeometry(QRect(10, 60, 131, 17));
        obj3_usebox = new QGroupBox(groupBox_8);
        obj3_usebox->setObjectName(QString::fromUtf8("obj3_usebox"));
        obj3_usebox->setGeometry(QRect(0, 40, 281, 121));
        obj3_showres = new QCheckBox(obj3_usebox);
        obj3_showres->setObjectName(QString::fromUtf8("obj3_showres"));
        obj3_showres->setGeometry(QRect(10, 50, 141, 17));
        obj3_distype = new QComboBox(obj3_usebox);
        obj3_distype->addItem(QString());
        obj3_distype->addItem(QString());
        obj3_distype->setObjectName(QString::fromUtf8("obj3_distype"));
        obj3_distype->setGeometry(QRect(150, 70, 61, 22));
        label_29 = new QLabel(obj3_usebox);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(0, 70, 71, 16));
        obj3_objpath = new QLineEdit(obj3_usebox);
        obj3_objpath->setObjectName(QString::fromUtf8("obj3_objpath"));
        obj3_objpath->setGeometry(QRect(0, 90, 91, 20));
        obj3_test = new QPushButton(obj3_usebox);
        obj3_test->setObjectName(QString::fromUtf8("obj3_test"));
        obj3_test->setGeometry(QRect(220, 60, 41, 23));
        obj3_lock = new QPushButton(obj3_usebox);
        obj3_lock->setObjectName(QString::fromUtf8("obj3_lock"));
        obj3_lock->setGeometry(QRect(220, 80, 41, 23));
        obj3_stop = new QPushButton(obj3_usebox);
        obj3_stop->setObjectName(QString::fromUtf8("obj3_stop"));
        obj3_stop->setGeometry(QRect(220, 100, 41, 23));
        obj3_resswitch = new QComboBox(obj3_usebox);
        obj3_resswitch->addItem(QString());
        obj3_resswitch->addItem(QString());
        obj3_resswitch->addItem(QString());
        obj3_resswitch->setObjectName(QString::fromUtf8("obj3_resswitch"));
        obj3_resswitch->setGeometry(QRect(150, 90, 61, 22));
        Button_obj3_OpenDialog = new QToolButton(obj3_usebox);
        Button_obj3_OpenDialog->setObjectName(QString::fromUtf8("Button_obj3_OpenDialog"));
        Button_obj3_OpenDialog->setGeometry(QRect(100, 70, 41, 21));
        pushButton_obj3_CaptureSample = new QPushButton(obj3_usebox);
        pushButton_obj3_CaptureSample->setObjectName(QString::fromUtf8("pushButton_obj3_CaptureSample"));
        pushButton_obj3_CaptureSample->setGeometry(QRect(100, 90, 41, 23));
        label_31 = new QLabel(groupBox_8);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(150, 60, 101, 16));
        obj3_objvalid = new QLabel(groupBox_8);
        obj3_objvalid->setObjectName(QString::fromUtf8("obj3_objvalid"));
        obj3_objvalid->setGeometry(QRect(190, 10, 30, 16));
        groupBox_9 = new QGroupBox(groupBox_3);
        groupBox_9->setObjectName(QString::fromUtf8("groupBox_9"));
        groupBox_9->setGeometry(QRect(370, 210, 381, 131));
        obj4_usecheck = new QCheckBox(groupBox_9);
        obj4_usecheck->setObjectName(QString::fromUtf8("obj4_usecheck"));
        obj4_usecheck->setGeometry(QRect(20, 30, 141, 17));
        obj4_usebox = new QGroupBox(groupBox_9);
        obj4_usebox->setObjectName(QString::fromUtf8("obj4_usebox"));
        obj4_usebox->setGeometry(QRect(20, 40, 341, 91));
        obj4_showres = new QCheckBox(obj4_usebox);
        obj4_showres->setObjectName(QString::fromUtf8("obj4_showres"));
        obj4_showres->setGeometry(QRect(0, 20, 151, 17));
        obj4_distype = new QComboBox(obj4_usebox);
        obj4_distype->addItem(QString());
        obj4_distype->addItem(QString());
        obj4_distype->setObjectName(QString::fromUtf8("obj4_distype"));
        obj4_distype->setGeometry(QRect(210, 40, 61, 22));
        label_32 = new QLabel(obj4_usebox);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(10, 40, 71, 16));
        obj4_objpath = new QLineEdit(obj4_usebox);
        obj4_objpath->setObjectName(QString::fromUtf8("obj4_objpath"));
        obj4_objpath->setGeometry(QRect(0, 60, 91, 20));
        obj4_test = new QPushButton(obj4_usebox);
        obj4_test->setObjectName(QString::fromUtf8("obj4_test"));
        obj4_test->setGeometry(QRect(280, 30, 41, 23));
        obj4_lock = new QPushButton(obj4_usebox);
        obj4_lock->setObjectName(QString::fromUtf8("obj4_lock"));
        obj4_lock->setGeometry(QRect(280, 50, 41, 23));
        obj4_stop = new QPushButton(obj4_usebox);
        obj4_stop->setObjectName(QString::fromUtf8("obj4_stop"));
        obj4_stop->setGeometry(QRect(280, 70, 41, 23));
        obj4_resswitch = new QComboBox(obj4_usebox);
        obj4_resswitch->addItem(QString());
        obj4_resswitch->addItem(QString());
        obj4_resswitch->addItem(QString());
        obj4_resswitch->setObjectName(QString::fromUtf8("obj4_resswitch"));
        obj4_resswitch->setGeometry(QRect(210, 60, 61, 22));
        Button_obj4_OpenDialog = new QToolButton(obj4_usebox);
        Button_obj4_OpenDialog->setObjectName(QString::fromUtf8("Button_obj4_OpenDialog"));
        Button_obj4_OpenDialog->setGeometry(QRect(120, 40, 91, 20));
        pushButton_obj4_CaptureSample = new QPushButton(obj4_usebox);
        pushButton_obj4_CaptureSample->setObjectName(QString::fromUtf8("pushButton_obj4_CaptureSample"));
        pushButton_obj4_CaptureSample->setGeometry(QRect(120, 60, 91, 23));
        obj4_objvalid = new QLabel(groupBox_9);
        obj4_objvalid->setObjectName(QString::fromUtf8("obj4_objvalid"));
        obj4_objvalid->setGeometry(QRect(190, 10, 30, 16));
        label_34 = new QLabel(groupBox_9);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(260, 30, 101, 16));
        groupBox_5 = new QGroupBox(centralWidget);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(40, 420, 361, 221));
        label_17 = new QLabel(groupBox_5);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(10, 20, 61, 16));
        exec_hand = new QGroupBox(groupBox_5);
        exec_hand->setObjectName(QString::fromUtf8("exec_hand"));
        exec_hand->setGeometry(QRect(0, 60, 351, 151));
        send_mvback2 = new QPushButton(exec_hand);
        send_mvback2->setObjectName(QString::fromUtf8("send_mvback2"));
        send_mvback2->setGeometry(QRect(300, 50, 51, 23));
        send_turnleft = new QPushButton(exec_hand);
        send_turnleft->setObjectName(QString::fromUtf8("send_turnleft"));
        send_turnleft->setGeometry(QRect(20, 20, 51, 23));
        send_mvforward2 = new QPushButton(exec_hand);
        send_mvforward2->setObjectName(QString::fromUtf8("send_mvforward2"));
        send_mvforward2->setGeometry(QRect(300, 20, 51, 23));
        send_mvleft = new QPushButton(exec_hand);
        send_mvleft->setObjectName(QString::fromUtf8("send_mvleft"));
        send_mvleft->setGeometry(QRect(100, 20, 41, 23));
        send_kickright = new QPushButton(exec_hand);
        send_kickright->setObjectName(QString::fromUtf8("send_kickright"));
        send_kickright->setGeometry(QRect(150, 50, 51, 23));
        send_mvforward1 = new QPushButton(exec_hand);
        send_mvforward1->setObjectName(QString::fromUtf8("send_mvforward1"));
        send_mvforward1->setGeometry(QRect(220, 20, 61, 23));
        send_mvright = new QPushButton(exec_hand);
        send_mvright->setObjectName(QString::fromUtf8("send_mvright"));
        send_mvright->setGeometry(QRect(100, 50, 41, 23));
        send_kickleft = new QPushButton(exec_hand);
        send_kickleft->setObjectName(QString::fromUtf8("send_kickleft"));
        send_kickleft->setGeometry(QRect(150, 20, 51, 23));
        send_turnright = new QPushButton(exec_hand);
        send_turnright->setObjectName(QString::fromUtf8("send_turnright"));
        send_turnright->setGeometry(QRect(20, 50, 51, 23));
        send_mvback1 = new QPushButton(exec_hand);
        send_mvback1->setObjectName(QString::fromUtf8("send_mvback1"));
        send_mvback1->setGeometry(QRect(220, 50, 61, 23));
        send_wan = new QPushButton(exec_hand);
        send_wan->setObjectName(QString::fromUtf8("send_wan"));
        send_wan->setGeometry(QRect(20, 80, 51, 23));
        send_mvforward3 = new QPushButton(exec_hand);
        send_mvforward3->setObjectName(QString::fromUtf8("send_mvforward3"));
        send_mvforward3->setGeometry(QRect(100, 80, 41, 23));
        send_standpose = new QPushButton(exec_hand);
        send_standpose->setObjectName(QString::fromUtf8("send_standpose"));
        send_standpose->setGeometry(QRect(150, 80, 51, 23));
        send_turnleft_big = new QPushButton(exec_hand);
        send_turnleft_big->setObjectName(QString::fromUtf8("send_turnleft_big"));
        send_turnleft_big->setGeometry(QRect(220, 80, 61, 23));
        send_turnright_big = new QPushButton(exec_hand);
        send_turnright_big->setObjectName(QString::fromUtf8("send_turnright_big"));
        send_turnright_big->setGeometry(QRect(300, 80, 51, 23));
        head_left = new QPushButton(exec_hand);
        head_left->setObjectName(QString::fromUtf8("head_left"));
        head_left->setGeometry(QRect(20, 110, 61, 23));
        head_right = new QPushButton(exec_hand);
        head_right->setObjectName(QString::fromUtf8("head_right"));
        head_right->setGeometry(QRect(110, 110, 81, 23));
        head_up = new QPushButton(exec_hand);
        head_up->setObjectName(QString::fromUtf8("head_up"));
        head_up->setGeometry(QRect(210, 110, 71, 21));
        head_down = new QPushButton(exec_hand);
        head_down->setObjectName(QString::fromUtf8("head_down"));
        head_down->setGeometry(QRect(300, 110, 51, 23));
        send_isaction = new QLabel(groupBox_5);
        send_isaction->setObjectName(QString::fromUtf8("send_isaction"));
        send_isaction->setGeometry(QRect(70, 20, 30, 16));
        label_5 = new QLabel(groupBox_5);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(110, 10, 241, 61));
        strategy_box = new QGroupBox(centralWidget);
        strategy_box->setObjectName(QString::fromUtf8("strategy_box"));
        strategy_box->setGeometry(QRect(410, 490, 411, 141));
        strategy_start = new QPushButton(strategy_box);
        strategy_start->setObjectName(QString::fromUtf8("strategy_start"));
        strategy_start->setGeometry(QRect(10, 20, 81, 23));
        label_19 = new QLabel(strategy_box);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(10, 50, 71, 16));
        strategy_type = new QComboBox(strategy_box);
        strategy_type->addItem(QString());
        strategy_type->addItem(QString());
        strategy_type->addItem(QString());
        strategy_type->setObjectName(QString::fromUtf8("strategy_type"));
        strategy_type->setGeometry(QRect(320, 20, 71, 23));
        strategy_imgdis = new QTextBrowser(strategy_box);
        strategy_imgdis->setObjectName(QString::fromUtf8("strategy_imgdis"));
        strategy_imgdis->setGeometry(QRect(10, 70, 141, 61));
        label_20 = new QLabel(strategy_box);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(160, 50, 71, 16));
        strategy_stop = new QPushButton(strategy_box);
        strategy_stop->setObjectName(QString::fromUtf8("strategy_stop"));
        strategy_stop->setGeometry(QRect(100, 20, 91, 23));
        strategy_clearinfo = new QPushButton(strategy_box);
        strategy_clearinfo->setObjectName(QString::fromUtf8("strategy_clearinfo"));
        strategy_clearinfo->setGeometry(QRect(200, 20, 111, 23));
        strategy_exec_orders = new QTextBrowser(strategy_box);
        strategy_exec_orders->setObjectName(QString::fromUtf8("strategy_exec_orders"));
        strategy_exec_orders->setGeometry(QRect(160, 70, 141, 61));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 847, 31));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "NPU_Roboteam", nullptr));
        groupBox->setTitle(QApplication::translate("MainWindow", "camera control", nullptr));
        label->setText(QApplication::translate("MainWindow", "\347\233\270\346\234\272\347\212\266\346\200\201", nullptr));
        camStatus->setText(QString());
        displayPause->setText(QApplication::translate("MainWindow", "\346\232\202\345\201\234\346\230\276\347\244\272", nullptr));
        displayContinue->setText(QApplication::translate("MainWindow", "\347\273\247\347\273\255\346\230\276\347\244\272", nullptr));
        pushButton_CaptureSample->setText(QApplication::translate("MainWindow", "\346\210\252\345\233\276", nullptr));
        groupBox_2->setTitle(QApplication::translate("MainWindow", "port control", nullptr));
        portName->setText(QApplication::translate("MainWindow", "com3", nullptr));
        portBaudRate->setText(QApplication::translate("MainWindow", "4800", nullptr));
        label_2->setText(QApplication::translate("MainWindow", "\344\270\262\345\217\243\345\217\267", nullptr));
        label_3->setText(QApplication::translate("MainWindow", "\346\263\242\347\211\271\347\216\207", nullptr));
        label_4->setText(QApplication::translate("MainWindow", "\344\270\262\345\217\243\347\212\266\346\200\201", nullptr));
        portOpen->setText(QApplication::translate("MainWindow", "\346\211\223\345\274\200\344\270\262\345\217\243", nullptr));
        portClose->setText(QApplication::translate("MainWindow", "\345\205\263\351\227\255\344\270\262\345\217\243", nullptr));
        portStatus->setText(QString());
        groupBox_3->setTitle(QApplication::translate("MainWindow", "initialize vision module", nullptr));
        groupBox_4->setTitle(QApplication::translate("MainWindow", "\347\233\256\346\240\2071", nullptr));
        obj1_usecheck->setText(QApplication::translate("MainWindow", "\345\220\257\347\224\250\350\257\245\346\250\241\345\235\227", nullptr));
        obj1_usebox->setTitle(QString());
        obj1_showres->setText(QApplication::translate("MainWindow", "\346\230\276\347\244\272\345\244\204\347\220\206\347\273\223\346\236\234", nullptr));
        obj1_distype->setItemText(0, QApplication::translate("MainWindow", "\347\220\203", nullptr));
        obj1_distype->setItemText(1, QApplication::translate("MainWindow", "\351\271\260\347\234\274", nullptr));

        obj1_distype->setCurrentText(QApplication::translate("MainWindow", "\347\220\203", nullptr));
        label_21->setText(QApplication::translate("MainWindow", "\347\233\256\346\240\207\346\240\267\346\234\254\350\267\257\345\276\204", nullptr));
        obj1_objpath->setText(QApplication::translate("MainWindow", "D:/Base/B.png", nullptr));
        obj1_test->setText(QApplication::translate("MainWindow", "\346\265\213\350\257\225", nullptr));
        obj1_lock->setText(QApplication::translate("MainWindow", "\351\224\201\345\256\232", nullptr));
        obj1_stop->setText(QApplication::translate("MainWindow", "\345\201\234\346\255\242", nullptr));
        obj1_resswitch->setItemText(0, QApplication::translate("MainWindow", "RGB", nullptr));
        obj1_resswitch->setItemText(1, QApplication::translate("MainWindow", "HS", nullptr));
        obj1_resswitch->setItemText(2, QApplication::translate("MainWindow", "SYN", nullptr));

        obj1_resswitch->setCurrentText(QApplication::translate("MainWindow", "RGB", nullptr));
        Button_obj1_OpenDialog->setText(QApplication::translate("MainWindow", "B", nullptr));
        pushButton_obj1_CaptureSample->setText(QApplication::translate("MainWindow", "Cap", nullptr));
        MoveR->setText(QApplication::translate("MainWindow", "right", nullptr));
        obj_door->setText(QApplication::translate("MainWindow", "D", nullptr));
        obj1_objpath_2->setText(QApplication::translate("MainWindow", "D:/Base/D.png", nullptr));
        haveblock->setText(QApplication::translate("MainWindow", "pro", nullptr));
        label_25->setText(QApplication::translate("MainWindow", "\345\233\276\347\211\207\346\234\211\346\225\210", nullptr));
        obj1_objvalid->setText(QString());
        groupBox_7->setTitle(QApplication::translate("MainWindow", "\347\233\256\346\240\2072", nullptr));
        obj2_usecheck->setText(QApplication::translate("MainWindow", "\345\220\257\347\224\250\350\257\245\346\250\241\345\235\227", nullptr));
        obj2_usebox->setTitle(QString());
        obj2_showres->setText(QApplication::translate("MainWindow", "\346\230\276\347\244\272\345\244\204\347\220\206\347\273\223\346\236\234", nullptr));
        obj2_distype->setItemText(0, QApplication::translate("MainWindow", "\347\220\203", nullptr));
        obj2_distype->setItemText(1, QApplication::translate("MainWindow", "\351\271\260\347\234\274", nullptr));

        label_26->setText(QApplication::translate("MainWindow", "\347\233\256\346\240\207\346\240\267\346\234\254\350\267\257\345\276\204", nullptr));
        obj2_objpath->setText(QString());
        obj2_test->setText(QApplication::translate("MainWindow", "\346\265\213\350\257\225", nullptr));
        obj2_lock->setText(QApplication::translate("MainWindow", "\351\224\201\345\256\232", nullptr));
        obj2_stop->setText(QApplication::translate("MainWindow", "\345\201\234\346\255\242", nullptr));
        obj2_resswitch->setItemText(0, QApplication::translate("MainWindow", "RGB", nullptr));
        obj2_resswitch->setItemText(1, QApplication::translate("MainWindow", "HS", nullptr));
        obj2_resswitch->setItemText(2, QApplication::translate("MainWindow", "SYN", nullptr));

        Button_obj2_OpenDialog->setText(QApplication::translate("MainWindow", "...", nullptr));
        pushButton_obj2_CaptureSample->setText(QApplication::translate("MainWindow", "Cap", nullptr));
        label_28->setText(QApplication::translate("MainWindow", "\345\233\276\347\211\207\346\234\211\346\225\210", nullptr));
        obj2_objvalid->setText(QString());
        groupBox_8->setTitle(QApplication::translate("MainWindow", "\347\233\256\346\240\2073", nullptr));
        obj3_usecheck->setText(QApplication::translate("MainWindow", "\345\220\257\347\224\250\350\257\245\346\250\241\345\235\227", nullptr));
        obj3_usebox->setTitle(QString());
        obj3_showres->setText(QApplication::translate("MainWindow", "\346\230\276\347\244\272\345\244\204\347\220\206\347\273\223\346\236\234", nullptr));
        obj3_distype->setItemText(0, QApplication::translate("MainWindow", "\347\220\203", nullptr));
        obj3_distype->setItemText(1, QApplication::translate("MainWindow", "\351\271\260\347\234\274", nullptr));

        label_29->setText(QApplication::translate("MainWindow", "\347\233\256\346\240\207\346\240\267\346\234\254\350\267\257\345\276\204", nullptr));
        obj3_objpath->setText(QString());
        obj3_test->setText(QApplication::translate("MainWindow", "\346\265\213\350\257\225", nullptr));
        obj3_lock->setText(QApplication::translate("MainWindow", "\351\224\201\345\256\232", nullptr));
        obj3_stop->setText(QApplication::translate("MainWindow", "\345\201\234\346\255\242", nullptr));
        obj3_resswitch->setItemText(0, QApplication::translate("MainWindow", "RGB", nullptr));
        obj3_resswitch->setItemText(1, QApplication::translate("MainWindow", "HS", nullptr));
        obj3_resswitch->setItemText(2, QApplication::translate("MainWindow", "SYN", nullptr));

        Button_obj3_OpenDialog->setText(QApplication::translate("MainWindow", "...", nullptr));
        pushButton_obj3_CaptureSample->setText(QApplication::translate("MainWindow", "Cap", nullptr));
        label_31->setText(QApplication::translate("MainWindow", "\345\233\276\347\211\207\346\234\211\346\225\210", nullptr));
        obj3_objvalid->setText(QString());
        groupBox_9->setTitle(QApplication::translate("MainWindow", "\347\233\256\346\240\2074", nullptr));
        obj4_usecheck->setText(QApplication::translate("MainWindow", "\345\220\257\347\224\250\350\257\245\346\250\241\345\235\227", nullptr));
        obj4_usebox->setTitle(QString());
        obj4_showres->setText(QApplication::translate("MainWindow", "\346\230\276\347\244\272\345\244\204\347\220\206\347\273\223\346\236\234", nullptr));
        obj4_distype->setItemText(0, QApplication::translate("MainWindow", "\347\220\203", nullptr));
        obj4_distype->setItemText(1, QApplication::translate("MainWindow", "\351\271\260\347\234\274", nullptr));

        label_32->setText(QApplication::translate("MainWindow", "\347\233\256\346\240\207\346\240\267\346\234\254\350\267\257\345\276\204", nullptr));
        obj4_objpath->setText(QString());
        obj4_test->setText(QApplication::translate("MainWindow", "\346\265\213\350\257\225", nullptr));
        obj4_lock->setText(QApplication::translate("MainWindow", "\351\224\201\345\256\232", nullptr));
        obj4_stop->setText(QApplication::translate("MainWindow", "\345\201\234\346\255\242", nullptr));
        obj4_resswitch->setItemText(0, QApplication::translate("MainWindow", "RGB", nullptr));
        obj4_resswitch->setItemText(1, QApplication::translate("MainWindow", "HS", nullptr));
        obj4_resswitch->setItemText(2, QApplication::translate("MainWindow", "SYN", nullptr));

        Button_obj4_OpenDialog->setText(QApplication::translate("MainWindow", "...", nullptr));
        pushButton_obj4_CaptureSample->setText(QApplication::translate("MainWindow", "Cap", nullptr));
        obj4_objvalid->setText(QString());
        label_34->setText(QApplication::translate("MainWindow", "\345\233\276\347\211\207\346\234\211\346\225\210", nullptr));
        groupBox_5->setTitle(QApplication::translate("MainWindow", "send order", nullptr));
        label_17->setText(QApplication::translate("MainWindow", "\346\211\247\350\241\214\345\212\250\344\275\234\344\270\255", nullptr));
        exec_hand->setTitle(QApplication::translate("MainWindow", "\346\211\213\345\212\250\346\211\247\350\241\214", nullptr));
        send_mvback2->setText(QApplication::translate("MainWindow", "\345\220\216\344\272\214", nullptr));
        send_turnleft->setText(QApplication::translate("MainWindow", "\345\267\246\350\275\254", nullptr));
        send_mvforward2->setText(QApplication::translate("MainWindow", "\345\211\215T", nullptr));
        send_mvleft->setText(QApplication::translate("MainWindow", "\345\267\246\347\247\273", nullptr));
        send_kickright->setText(QApplication::translate("MainWindow", "\345\217\263\350\270\242", nullptr));
        send_mvforward1->setText(QApplication::translate("MainWindow", "\345\211\215", nullptr));
        send_mvright->setText(QApplication::translate("MainWindow", "\345\217\263\347\247\273", nullptr));
        send_kickleft->setText(QApplication::translate("MainWindow", "\345\267\246\350\270\242", nullptr));
        send_turnright->setText(QApplication::translate("MainWindow", "\345\217\263\350\275\254", nullptr));
        send_mvback1->setText(QApplication::translate("MainWindow", "\345\220\216\344\270\200", nullptr));
        send_wan->setText(QApplication::translate("MainWindow", "\345\274\257\350\205\260", nullptr));
        send_mvforward3->setText(QApplication::translate("MainWindow", "\345\211\215L", nullptr));
        send_standpose->setText(QApplication::translate("MainWindow", "\346\201\242\345\244\215", nullptr));
        send_turnleft_big->setText(QApplication::translate("MainWindow", "\345\244\247TL", nullptr));
        send_turnright_big->setText(QApplication::translate("MainWindow", "\345\244\247TR", nullptr));
        head_left->setText(QApplication::translate("MainWindow", "\345\244\264\345\267\246", nullptr));
        head_right->setText(QApplication::translate("MainWindow", "\345\244\264\345\217\263", nullptr));
        head_up->setText(QApplication::translate("MainWindow", "\345\244\264\344\270\212", nullptr));
        head_down->setText(QApplication::translate("MainWindow", "\345\244\264\344\270\213", nullptr));
        send_isaction->setText(QString());
        label_5->setText(QApplication::translate("MainWindow", "\345\246\202\346\236\234\346\262\241\346\234\211\346\211\247\350\241\214\345\212\250\344\275\234,\350\257\267\345\205\263\351\227\255\344\270\262\345\217\243,\345\271\266\344\275\277\347\224\250\345\205\266\344\273\226\350\275\257\344\273\266\342\200\235\346\277\200\346\264\273\342\200\234\345\212\250\344\275\234", nullptr));
        strategy_box->setTitle(QApplication::translate("MainWindow", "strategists", nullptr));
        strategy_start->setText(QApplication::translate("MainWindow", "\345\274\200\345\247\213\346\211\247\350\241\214", nullptr));
        label_19->setText(QApplication::translate("MainWindow", "\345\233\276\345\203\217\345\244\204\347\220\206\344\277\241\346\201\257", nullptr));
        strategy_type->setItemText(0, QApplication::translate("MainWindow", "\346\240\267\344\276\213\347\255\226\347\225\245", nullptr));
        strategy_type->setItemText(1, QApplication::translate("MainWindow", "\347\202\271\347\220\203", nullptr));
        strategy_type->setItemText(2, QApplication::translate("MainWindow", "\345\256\210\351\227\250", nullptr));

        strategy_type->setCurrentText(QApplication::translate("MainWindow", "\346\240\267\344\276\213\347\255\226\347\225\245", nullptr));
        strategy_imgdis->setHtml(QApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'MS Shell Dlg 2'; font-size:8pt;\"><br /></p></body></html>", nullptr));
        label_20->setText(QApplication::translate("MainWindow", "\346\211\247\350\241\214\345\221\275\344\273\244", nullptr));
        strategy_stop->setText(QApplication::translate("MainWindow", "\345\201\234\346\255\242\346\211\247\350\241\214", nullptr));
        strategy_clearinfo->setText(QApplication::translate("MainWindow", "\346\270\205\347\251\272\344\277\241\346\201\257", nullptr));
        strategy_exec_orders->setHtml(QApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'MS Shell Dlg 2'; font-size:8pt;\"><br /></p></body></html>", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
